# Generated by Django 4.1.2 on 2022-10-15 04:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='contents',
            new_name='content',
        ),
        migrations.AddField(
            model_name='diary',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 15, 4, 45, 3, 287124, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
